try:
    num = 10
except:
    print("Error occurred")
else:
    print("No exception, num is", num)
